### ISSUE TITLE
Saved layout are not loaded correct

### ISSUE THREAD

**Issue by fzerorubigd** [fzerorubigd/tmass#8]
After each split, I need to apply the layout, for saved layout like this to work : 
```yaml
name: "the-ultimate-panel"
windows:
- name: ~
  layout: 0352,272x67,0,0{40x67,0,0,0,160x67,41,0[160x23,41,0{54x23,41,0,2,48x23,96,0,5,56x23,145,0,4},160x43,41,24{39x43,41,24[39x26,41,24,3,39x16,41,51,7],120x43,81,24[120x21,81,24,6,120x21,81,46,8]}],70x67,202,0,1}
  panes:
  - commands:
    - echo 1
    root: ~
  - commands:
    - echo 2
    root: ~
  - commands:
    - echo 3
    root: ~
  - commands:
    - echo 4
    root: ~
  - commands:
    - echo 5
    root: ~
  - commands:
    - echo 6
    root: ~
  - commands:
    - echo "Default CMD"
    root: ~
  - commands:
    - echo "Default CMD"
    focus: true
    root: ~
  - commands:
    - htop
    root: ~
- name: ~/redmine
  layout: 79b2,272x67,0,0{136x67,0,0[136x33,0,0,9,136x33,0,34,11],135x67,137,0,10}
  panes:
  - commands:
    - echo "Default CMD"
    root: ~
  - commands:
    - su - redmine
    focus: true
    root: ~
  - commands:
    - echo "Default CMD"
    root: ~
```
